name: 'Proproject Automation'
on:
  issues:
    types: [opened]
jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: 'Automate adding issues to Backlog'
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'issues'
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/purelyfortesting/projects/1
          GITHUB_PROJECT_COLUMN_NAME: 'Pending Review'
