name: 'Proproject Automation'
on:
  - workflow_dispatch
jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: 'Collect all issues'
      uses: dhruvkb/issue-projector@0.0.1
      with:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        ORG_NAME: 'purelyfortesting'
        PROJECT_NAME: 'Proproject'
        COLUMN_NAME: 'Pending_Review'
