name: 'Proproject Automation'
on:
  schedule:
  - cron: "0/5 * * * *"
jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: 'Trash'
      uses: subhamX/github-project-bot@v1.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: 'Pending Review'
        PROJECT_URL: https://github.com/orgs/purelyfortesting/projects/1
        REPO_URL: https://github.com/purelyfortesting/trash
    - name: 'Rubbish'
      uses: subhamX/github-project-bot@v1.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: 'Pending Review'
        PROJECT_URL: https://github.com/orgs/purelyfortesting/projects/1
        REPO_URL: https://github.com/purelyfortesting/rubbish
    - name: 'Garbage'
      uses: subhamX/github-project-bot@v1.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: 'Pending Review'
        PROJECT_URL: https://github.com/orgs/purelyfortesting/projects/1
        REPO_URL: https://github.com/purelyfortesting/garbage
